modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="thicc_sticc"
version="1.1.0"
displayName="Thicc Sticc"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Raymond Steen"
description='''
thicc sticc
'''

[[dependencies.thicc_sticc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




